version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "LaioBomfimDev"
    assignees:
      - "LaioBomfimDev"
    commit-message:
      prefix: "backend"
      include: "scope"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "LaioBomfimDev"
    assignees:
      - "LaioBomfimDev"
    commit-message:
      prefix: "frontend"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "LaioBomfimDev"
    assignees:
      - "LaioBomfimDev"